### ISSUE TITLE
Error registering for user account: _send_mail() got multiple values for argument 'request'

### ISSUE THREAD

**Issue by hjwp** [jambonrose/DjangoUnleashed-1.8#2]
Maybe I'm not meant to just run the site off master?

http://dpaste.com/1N5NMX2  

freshly created virtualenv on windows.  i know, i know, but the 15.04 upgraded borked ubuntu on my laptop.

**Comment by jambonrose** [comment]
I think it's very nice of you to try and blame the OS for my own errors. :D

This is a clear example of why you always run the test suite after even very small changes.

Will update this shortly.

**Comment by jambonrose** [comment]
I believe this now works correctly.

Thanks again for the input!
